AllCops:
  TargetRubyVersion: 2.4
  Excludes:
    - Rakefile
    - vendor/**/*
    - bin/**/

Documentation:
  # don't require classes to be documented
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

AlignParameters:
  # allow for multi-line methods to have normal indentation.
  # for example:
  #
  # Person.where(
  #   first_name: 'tom',
  #   last_name: 'foolery'
  # )
  EnforcedStyle: with_fixed_indentation

Layout/AlignParameters:
  # allow for end of if to be aligned with a variable.
  # for example:
  #
  # foo = if a == b
  #   'bar'
  # else
  #   'baz'
  # end
  EnforcedStyle: with_fixed_indentation

Layout/ElseAlignment:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

ClassAndModuleChildren:
  # ok to use compact style when modules are predefined.
  # for example the following is fine so long as we're sure that
  # module MDB has already been required/defined.
  #
  # class Foo::Bar; end
  Enabled: false

Metrics/BlockLength:
  # Certain DSL use blocks and can be lengthy
  Exclude:
    - 'grape-apiary.gemspec'
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": ()
    "%w": ()
